#gpio export 4 up
#gpio export 17 up
#gpio export 18 up
#gpio mode 4 up
#gpio mode 17 up
#gpio mode 18 up
echo "4" > /sys/class/gpio/export 
echo "17" > /sys/class/gpio/export 
echo "18" > /sys/class/gpio/export 
gpio mode 4 up
gpio mode 17 up
gpio mode 18 up
